import React, { useMemo, useState } from 'react';
import { AppLayout } from '../layouts/AppLayout';
import { Badge, Button, Card, EmptyState, ProgressBar, SearchInput, SectionHeader, StatCard, Table } from '../components/ui';

const modules = {
  properties:{title:'Property portfolio',subtitle:'Multi-brand operating view · local tax, timezone and currency aware',icon:'🏨',stats:[['Active properties','12'],['Room inventory','2,846'],['Readiness','96%']],rows:[['The Aura Mumbai','India · INR','86%','Operating'],['Azure Cove Goa','India · INR','91%','Operating'],['Nexgile Dubai Marina','UAE · AED','78%','Onboarding']]},
  rooms:{title:'Rooms & operations',subtitle:'Live readiness, digital keys, housekeeping and maintenance',icon:'🛏️',stats:[['Ready now','428'],['Inspection queue','18'],['Key battery alerts','6']],rows:[['1204 · Deluxe Sea','Ready','N. Shah','Digital key active'],['0718 · Club King','Inspected','R. Das','Arrival 14:00'],['0931 · Suite','Maintenance','—','AC ticket #M-481']]},
  housekeeping:{title:'Housekeeping command',subtitle:'Tasks, inspections and automated escalation',icon:'🧹',stats:[['Open tasks','34'],['SLA met','98.2%'],['Rooms ready','428']],rows:[['HK-1948','1204 · Deluxe','In progress','Due 11:20'],['HK-1952','0718 · Club King','Inspection','Due 11:35'],['HK-1961','0911 · Suite','Assigned','Due 12:00']]},
  maintenance:{title:'Maintenance & assets',subtitle:'Preventive maintenance with guest-impact alerts',icon:'🔧',stats:[['Open cases','12'],['Critical','2'],['Preventive due','8']],rows:[['M-481','0931 · Suite','Critical','HVAC performance'],['M-472','L12 lift','In progress','Noise event'],['M-463','Pool pump','Scheduled','Due today']]},
  channels:{title:'Distribution hub',subtitle:'Inventory, rate parity and real-time channel synchronization',icon:'🌐',stats:[['Connected channels','28'],['Parity alerts','3'],['Sync health','99.8%']],rows:[['Booking.com','Live','2 min ago','₹18.4L'],['Expedia','Live','2 min ago','₹12.1L'],['Amadeus GDS','Retrying','7 min ago','₹8.7L']]},
  marketplace:{title:'Nexgile Marketplace',subtitle:'Hotels, flights, cars, dining and experiences in one itinerary',icon:'🛒',stats:[['Live products','1.2M'],['Cart conversion','6.8%'],['Package savings','18%']],rows:[['Azure Cove Goa','Hotel · 4 nights','₹48,600','Available'],['Mumbai → Goa','Flight · Economy','₹8,450','Available'],['Konkan food trail','Experience · 2 guests','₹3,200','Limited']]},
  concierge:{title:'AI Concierge',subtitle:'Contextual travel assistance with human override and escalation',icon:'✦',stats:[['Active conversations','47'],['Auto-resolved','82%'],['CSAT','4.8/5']],rows:[['Ananya Kapoor','Airport transfer','AI proposed · needs confirmation','Now'],['Marco Bianchi','Late checkout','Escalated to Front Desk','3 min ago'],['Riya Mehta','Restaurant recommendation','Resolved','9 min ago']]},
  forecasting:{title:'AI demand forecast',subtitle:'Demand signals, event impact, confidence and approval guardrails',icon:'✨',stats:[['30-day occupancy','89.2%'],['Forecast confidence','94%'],['Pricing actions','7']],rows:[['Fri 20 Sep','92% demand','Concert uplift +14%','Approve ₹15,900'],['Sat 21 Sep','97% demand','Compression risk','Approve ₹18,500'],['Mon 23 Sep','68% demand','Corporate pace','Hold ₹10,900']]},
  competitors:{title:'Competitor intelligence',subtitle:'Rate shop, availability and parity anomalies',icon:'◈',stats:[['Tracked set','8'],['Price position','+3.1%'],['Alerts','3']],rows:[['Harbour Grand','₹16,800','Sold 86%','+₹900 vs us'],['The Meridian','₹15,950','Sold 81%','+₹50 vs us'],['Palm House','₹14,500','Sold 77%','−₹1,400 vs us']]},
  analytics:{title:'Executive analytics',subtitle:'Portfolio performance, pace and predictive signals',icon:'📊',stats:[['Portfolio RevPAR','₹10,899'],['Guest NPS','72'],['Ancillary mix','19.6%']],rows:[['Mumbai','₹12,940 RevPAR','89% occupancy','Ahead of plan'],['Goa','₹9,880 RevPAR','84% occupancy','Ahead of plan'],['Dubai','AED 642 RevPAR','78% occupancy','Watch pace']]},
  trips:{title:'Live trips',subtitle:'Itinerary, disruption management, groups and live travel documents',icon:'✈️',stats:[['Upcoming trips','3'],['Live now','1'],['Trip credit','₹2,400']],rows:[['Goa wellbeing escape','18–22 Sep','Hotel + flight + dining','Confirmed'],['Dubai client summit','06–09 Oct','Flight + transfer','Pending approval'],['Bengaluru weekend','17–19 Oct','Hotel','Saved']]},
  documents:{title:'Travel document vault',subtitle:'Encrypted passport, visa, insurance and booking documents',icon:'📂',stats:[['Verified documents','8'],['Expiring soon','1'],['Trip documents','12']],rows:[['Passport','Verified','Expires May 2030','Ready'],['UAE visa','Verified','Expires Nov 2027','Ready'],['Travel insurance','Action needed','Renewal in 18 days','Review']]},
  wallet:{title:'Travel wallet',subtitle:'Multi-currency balances, cards, credits and payment preferences',icon:'💳',stats:[['Wallet balance','₹18,240'],['Reward value','₹6,950'],['Currencies','5']],rows:[['INR balance','₹18,240','Default','Active'],['USD travel card','$240.20','FX lock enabled','Active'],['Travel credit','₹2,400','Expires 30 Sep','Use now']]},
  loyalty:{title:'Nexgile Rewards',subtitle:'Tier benefits, points, partners, referrals and cashback',icon:'🏆',stats:[['Tier','Platinum'],['Available points','84,600'],['Next reward','5,400 pts']],rows:[['Azure Cove stay','+4,860 pts','Posted','09 Sep'],['Partner dining','+620 pts','Posted','08 Sep'],['Weekend bonus','+1,200 pts','Pending','10 Sep']]},
  corporate:{title:'Corporate travel',subtitle:'Policy, preferred vendors, budgets and duty of care',icon:'💼',stats:[['Policy compliance','96%'],['Budget remaining','₹42.8L'],['Travellers in trip','128']],rows:[['Q3 product summit','₹9.8L','Within budget','Approved'],['EMEA sales week','₹14.1L','2 exceptions','Review'],['New hire travel','₹3.4L','Within budget','Approved']]},
  approvals:{title:'Approvals centre',subtitle:'Configurable rules, escalations and accountable human decisions',icon:'✓',stats:[['Awaiting review','9'],['Auto-approved','74%'],['SLA at risk','2']],rows:[['TR-8493 · Dubai client summit','₹68,400','Policy exception','Review'],['PR-281 · Weekend rate guardrail','₹18,500 ADR','Revenue approval','Review'],['EX-920 · Taxi receipt','₹2,870','Expense approval','Approve']]},
  expenses:{title:'Expenses & reconciliation',subtitle:'Receipts, VAT, reimbursements, cards and finance controls',icon:'🧾',stats:[['Unsubmitted','5'],['Awaiting reimbursement','₹24,680'],['VAT recoverable','₹8,420']],rows:[['EX-920','Airport transfer','₹2,870','Pending approval'],['EX-915','Client dinner','₹8,400','Policy check'],['EX-901','Flight change','₹13,410','Reimbursing']]},
  users:{title:'Users & role access',subtitle:'Tenant-aware RBAC, consent and operating preferences',icon:'👤',stats:[['Active users','684'],['Roles configured','12'],['Consent reviews','4']],rows:[['Priya Menon','RevenueManager','Azure Cove Goa','Active'],['Omar Khalid','PropertyAdmin','Dubai Marina','Active'],['Sofia Costa','CorporateManager','Cloudline Corp','Active']]},
  integrations:{title:'Integrations',subtitle:'Adapters, webhooks and operational health across the ecosystem',icon:'🔌',stats:[['Connected','36'],['Webhooks today','18,492'],['Error queue','7']],rows:[['Stripe Payments','Operational','5,811 events','Connected'],['Amadeus','Operational','3,204 events','Connected'],['WhatsApp','Degraded','2 retries','Investigate']]},
  'api-audit':{title:'API & audit trail',subtitle:'Idempotent actions, retries, reconciliation and traceable change history',icon:'◌',stats:[['API success','99.96%'],['Idempotency matches','24'],['Audit events','32,198']],rows:[['evt_48192','booking.create','Idempotent replay','Recovered'],['evt_48188','payment.capture','Stripe · 200','Complete'],['evt_48175','channel.sync','Amadeus retry 2/3','Monitoring']]},
  settings:{title:'Settings & preferences',subtitle:'Brand, localization, quiet hours, notifications and AI oversight',icon:'⚙️',stats:[['Locale','en-IN'],['Currency','INR'],['AI override','Enabled']],rows:[['Notifications','Quiet hours 22:00–07:00','Push + email','Configured'],['Localization','Asia/Kolkata · GST','English, Hindi','Configured'],['AI governance','Human approval on pricing','Version 2.4','Active']]}
};

export default function ModulePage({page,onNavigate}){const [query,setQuery]=useState('');const [toast,setToast]=useState('');const m=modules[page]||modules.analytics;const rows=useMemo(()=>m.rows.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase())),[m,query]);return <AppLayout activePage={page} onNavigate={onNavigate} title={m.title} subtitle={m.subtitle}><SectionHeader title={m.title} subtitle="Live mock workspace · API-ready data contract" actions={<><Button variant="secondary" onClick={()=>setToast('Export queued — a report will be prepared shortly.')}>Export</Button><Button onClick={()=>setToast('Action saved. The audit trail has been updated.')}>New action</Button></>}/>{toast&&<div className="toast" onClick={()=>setToast('')}>{toast}</div>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:18,marginBottom:22}}>{m.stats.map(([label,value],i)=><StatCard key={label} label={label} value={value} icon={i===0?m.icon:'✦'} change={i===1?3.2:undefined} onClick={()=>setToast(`${label}: detailed drill-down opened.`)}/>)}</div><div style={{display:'grid',gridTemplateColumns:'minmax(0,1.7fr) minmax(280px,.8fr)',gap:22}}><Card><div style={{display:'flex',justifyContent:'space-between',gap:16,marginBottom:18,alignItems:'center'}}><b>Operational queue</b><div style={{width:240}}><SearchInput value={query} onChange={setQuery} placeholder="Search this workspace"/></div></div>{rows.length?<Table data={rows.map((r,i)=>({id:r[0],detail:r[1],signal:r[2],status:r[3]}))} columns={[{key:'id',label:'Item'},{key:'detail',label:'Detail'},{key:'signal',label:'Signal'},{key:'status',label:'Status',render:v=><Badge status={v==='Operational'||v==='Active'||v==='Ready'||v==='Confirmed'||v==='Approved'||v==='Complete'?'active':'pending'} label={v}/>}]} onRowClick={r=>setToast(`${r.id} opened in its detailed view.`)}/>:<EmptyState title="No matching records" message="Try a different search term."/>}</Card><Card><b>AI operating signal</b><p style={{fontSize:14,color:'var(--text-muted)',lineHeight:1.55}}>TravAI has connected demand, service and operational context. Recommendations remain reviewable and every decision is logged.</p><ProgressBar label="Data confidence" value={94} color="#14b8a6"/><div style={{height:16}}/><ProgressBar label="Workflow automation" value={78} color="#6366f1"/><div style={{marginTop:20}}><Button variant="secondary" size="sm" onClick={()=>setToast('AI rationale and source signals are ready for review.')}>View rationale</Button></div></Card></div></AppLayout>}
